FROM oven/bun:latest as build

WORKDIR /build

COPY . .

RUN bun install

RUN bun run compile linux-x64-baseline --no-version-tag

FROM debian:stable-slim

RUN apt-get update && apt-get install -y ca-certificates openssl

WORKDIR /opt/delivr-api

COPY --from=build /build/build/bin/delivr-api-linux-x64-baseline /usr/local/bin/delivr-api

RUN chmod u+x /usr/local/bin/delivr-api

EXPOSE 14123/tcp

ENTRYPOINT ["delivr-api"]